### ISSUE TITLE
ID seharusnya Id

### ISSUE THREAD

**Issue by crowdemichael** [crowdeco/bima#3]
protobuf generate sebagai Id bukan ID, akan timbul masalah ketika berurusan dengan copier, misalkan copy foreign key CategoryID << CategoryId (dari protobuf)

**Comment by crowdemichael** [comment]
```
{
  "code": 400,
  "data": {
    "id": "",
    "name": "John Doe",
    "categoryId": "5ebfe723-d3c9-417f-be67-0f4209d88310"
  },
  "message": "Error 1452: Cannot add or update a child row: a foreign key constraint fails (`quiz_servo`.`module`, CONSTRAINT `fk_module_category` FOREIGN KEY (`category_id`) REFERENCES `category` (`id`) ON UPDATE CASCADE)"
}
```

**Comment by surya4crowde** [comment]
Dari Gorm konvensinya pakai ID mike

**Comment by crowdemichael** [comment]
benefit diluar convention saya lihat tidak ada ketimbang dev harus maintain ID atau beberapa ID (foreign key) setiap domain agar tak terlewatkan untuk diassign

supaya konsisten ID maka copier harus diupgrade

**Comment by crowdemichael** [comment]
https://github.com/crowdeco/quiz-service/blob/be647e5f1188d004806406e379ff9b423d4785d6/utils/copier.go#L238
ini sudah saya buat patch copier, `CategoryID` akan dicopy ke `CategoryId` vice versa

silahkan mau pilih yang mana

**Comment by surya4crowde** [comment]
Ok ini gue coba riset dulu untuk solusinya mike

**Comment by surya4crowde** [comment]
Done
