### ISSUE TITLE
Titip

### ISSUE THREAD

**Issue by crowdemichael** [crowdeco/bima#7]
- sering muncul di awal run app, elastic: Error 404 (Not Found): no such index [<nama_index>] [type=index_not_found_exception]
- 2 kata nama modul menjadi tergabung saat register contoh accounttypes

**Comment by surya4crowde** [comment]
1. Ini karena dibikin verbose aja sih mike

```go
	_, err := m.Elasticsearch.DeleteIndex(v.TableName()).Do(m.Context)
	if err != nil {
		m.Logger.Error(fmt.Sprintf("%+v", err))
	}
```

2. Ini konsernnya bagaimana ya?

**Comment by crowdemichael** [comment]
yang ke 2 saat register modul

**Comment by crowdemichael** [comment]
closed, untuk package name 2 kata tetap digabung
